Update node_clone to 1.0 (from 1.0-rc2)
govCMS/GovCMS7 pull request #508
Opened 2017-06-14 21:27 UTC by tobybellwood

https://www.drupal.org/project/node_clone/releases/7.x-1.0

Release notes
Changes since 7.x-1.0-rc4:
#1325028 by pwolanin, ipaq3870: fix for Not cloning menu entries
#2616506 by rgristroph: Pass clone_context into hook_clone_node_alter()

Changes since 7.x-1.0-rc3:
#2615534 by Arkener: Clone link in views not working

Changes since 7.x-1.0-rc2:
#2376203 by pwolanin: Add a method to suppress advanced rednering on the view field
#450000 by StoraH, skyredwang, Itangalo: Rules Integration (action) with Node Clone
#2279659 by pwolanin: Point users to the Field Collection Node Clone module
#1903272 by pwolanin, Matthieu Bilbille, tyler.frankenstein: Fix clone operation on admin/content for users without "Administer Content" permission
#2342737 by pwolanin, cashwilliams: Harden CSRF token by including the node ID
#1982874 by jenlampton, pwolanin: fix for Confusing help text on node clone settings page

2017-06-23 05:52 UTC, pandaskii requested changes
Happy for this PR to be passed onto testing before release

@ruwanl @Venkata-modgu

2017-06-27 06:53 UTC, tobybellwood commented
Test This

2017-06-28 01:18 UTC, Venkata-modgu commented
Test passed.

2017-06-30 00:41 UTC, pandaskii approved these changes

2017-07-04 10:09 UTC, merged