Update chosen to 2.1 (from 2.0-beta4)
govCMS/GovCMS7 pull request #510
Opened 2017-06-14 22:21 UTC by tobybellwood

https://www.drupal.org/project/chosen/releases/7.x-2.1

Release notes
This release includes minor additions.

Changes since 7.x-2.0:
#2855775 by renatog: Created help section
#2492251 by sseguin, brockfanning: No CSS loaded when the lib is downloaded with bower
#2831116 by renatog: Coding Standards

Release notes
This release includes minor bug fixes and improvements.

Changes since 7.x-2.0-beta5:
#2398291 by m.abdulqader, mr.york: Right to Left Support
#2534756 by sseguin, villette, mr.york, brockfanning: Enable Chosen on admin page only
#2790897 by joelpittet: Let the width be flexible
#2457619 by hgoto, Erik Frèrejean, m4olivei: Library defined in "JS_DEFAULT" group
#2083147 by RaF7, silversk8r, Hydra: Allow deselect on single selects

Release notes
This release includes minor bug fixes and improvements.

It provides a way to disable loading the module's css on specific themes. An update hook is included to change the configuration to the new method.

Changes since 7.x-2.0-beta4:
#2410783 by mr.york, dmsmidt: Make the 'Use the default chosen theme' a per theme setting
#2117827 by stupiddingo, Елин Й., maximpodorov, xpersonas: "None" showing up as an option in multiselect
#1591908 by bago, pcambra, jmuzz | alexverb: Added Variable module integration (via hook_variable_info).

2017-06-23 05:38 UTC, pandaskii requested changes
Happy for this PR to be passed onto testing before release

@ruwanl @Venkata-modgu

2017-06-27 06:41 UTC, tobybellwood commented
test this

2017-06-27 22:59 UTC, Venkata-modgu commented
Test passed.

2017-06-27 23:49 UTC, pandaskii approved these changes

2017-07-04 10:08 UTC, merged