Update menu_attributes to 1.0 (from 1.0-rc2)
govCMS/GovCMS7 pull request #512
Opened 2017-06-15 02:41 UTC by tobybellwood

https://www.drupal.org/project/menu_attributes/releases/7.x-1.0

Release notes
Changes since 7.x-1.0-rc3:

#2390755 by Nemanja, joelpittet, scotself: Different permissions suggestion and empty fieldsets
#2660606 by tom friedhof: Warning: explode() expects parameter 2 to be string, array given in menu_attributes_preprocess_menu_link()
#2368087: Make 'Menu link attributes' collapsed by default

Release notes
Changes since 7.x-1.0-rc2:

#2185403 by juanjo_dv: Fixed Localizable options for link target.
80 char coding standards
#1488960 by andrewmacpherson, michaek | JamesRobertson: Added Attributes for LI element.
#1627806 by d.clarke | clavigne: Added Move Attributes into its own fieldset within the Menu settings area.
#1894772 by amateescu, alberto56: Fixed hook_menu_attribute_info() API example.
#1909564 by opi: Fixed Typo in menu_attributes_menu_attribute_info() comment.
#1761804 by osopolar, quicksketch: Do not add empty classes produced by leading, trailing or double spaces.
#1077426 by cweagans: Followup: Fix permission checks.
#1886014 by Berdir: Fixed Argument 2 passed to _menu_attributes_form_alter() must be an array, null given.

2017-06-23 03:55 UTC, pandaskii requested changes
Happy for this PR to be passed onto testing before release

@ruwanl @Venkata-modgu

2017-06-23 05:55 UTC, tobybellwood commented
test this

2017-06-27 02:48 UTC, Venkata-modgu commented
Test Passed.

2017-06-27 23:48 UTC, pandaskii approved these changes

2017-07-04 10:08 UTC, merged