Automated testing
govCMS/GovCMS7 pull request #522
Opened 2017-07-11 06:39 UTC by barbun

Behold TL;DR! This is a rather big chunk of work that contains significant enhancements to the existing govCMS automated build and testing tools. The majority of the changes is focused on Behat testing with some other updates tagging along to enable for broader experience with the test scenarios.

**Key changes:**
- Increased testing for the govCMS distribution, which will provide greater confidence when merging PRs. 
- Expanded on the ways in which tests can be written
- Provided a framework that can be extended to write more tests
- Updated the toolset to stable versions
- Fixed (or indicated) some general issues found along the way (see “Additional changes”)

The test coverage is now estimated at approx. 75% of the functionality with the number of Behat tests increasing from 16 to 38 with addition of 1 PHPUnit test.

# Build Tools
The govCMS build toolset has been upgraded with newer versions to benefit from the latest features, solutions and bugfixes. The *composer.json* file enclosed in build folder is responsible for assembling all the needed parts to run the build process. The following changes were implemented to composer.json:
- Updated Drupal Behat extension to latest stable release
- Removed Drupal Driver library as it became a dependency of Drupal Behat extension
- Updated Goutte screen scraping library for PHP to latest stable release
- Removed Guzzle PHP library because it is now a dependency for Goutte
- Removed PHP CodeSniffer library as it is now pulled as a dependency
- Updated PHPMD library to latest stable release
- Removed PDepend library as it is now pulled in as a dependency of PHP Depend
- Updated PHPLOC tool to a stable version. Note, later versions exist but need testing.
- Updated PHP Copy/Paste detector to latest stable
- Added PHPunit 5.7.

As this combination of tools and libraries can be fragile, for future maintenance and updates the newer versions should be tested to work together and provide the expected results before committing them into *composer.lock*

The composer.lock file has been updated accordingly to lock the tested versions of the tools.

# Build script
GovCMS uses Phing as a PHP project build tool. All the custom steps and logic for creating govCMS project are scripted in XML format and contained within *build/phing/build.xml* file. The script has been augmented to add two additional steps: 

- Run Behat tests with two different profiles (explained below)
- Run PHPUnit tests (explained below)

# Drupal API driver
Previously, Behat was running using Drush driver (read more [here](http://behat-drupal-extension.readthedocs.io/en/3.1/drush.html)). As the scenarios advanced it became necessary to introduce Drupal API driver (read more read more [here](http://behat-drupal-extension.readthedocs.io/en/3.1/drupalapi.html)) to unlock the full potential of testing. In a nutshell, the Drupal API driver allows Behat to create users, roles, nodes, vocabularies and taxonomy terms on the fly. The only drawback of such, compared to others, is that it cannot be run on a different server than the site being tested. This is not an issue with the current approach for govCMS builds using Jenkins.

This resulted in re-writing the default Behat profile (*build/tests/behat/behat.yml*) to use Drupal API driver.

# PHPUnit support
Support for PHP unit tests has been added, with the *phpunit.conf* and *bootstrap_phpunit.inc* files being placed in build/tests/phpunit. Tests are provided with a fully bootstrapped Drupal environment and will use the default site's database (installation should have run).

The tests make use of the TDD7 (Test Driven Development for Drupal 7), a module hosted at https://github.com/edward-murrell/tdd7, which provides mock versions of a good number of Drupal functions. TDD7 doesn't need to be enabled in the Drupal installation. Some additional mocks were written and these could be submitted back upstream (although the project seems to be inactive).
With the added configuration, docroot is not checked for tests. Rather, the modules directory next to the docroot and its contents are searched, so tests will only be run for the custom govCMS modules. Files containing PHPunit tests should match the pattern '*Test.php'.

As the pilot, Unit tests have been written for the Iconomist module and together with TDD7's self tests they can be invoked from the parent directory of the build with the following command:
```
build/bin/phing -f build/phing/build.xml test:phpunit
```
The iconomistTest.php may be used as a pattern for writing new tests for other modules - it shows how to include TDD7, mock Drupal core functions and implement tests. The heart of the implementation is the use of a namespace, within which functions are defined with the same name as those being overridden. Since the invocations in Drupal itself aren't prefixed with namespaces, the definitions in the file's namespace can override them. These then invoke the static methods defined in TDD7.

The *phpunit.conf* file includes configuration for generating code coverage information as well. This is commented out by default as it's not needed for Jenkins. When enabled, the output will be placed in a */coverage* directory (next to docroot).

# Custom Behat steps
The Behat/Mink and Drupal Extension provide the standard set of step definitions that interpret the human-readable language into a logical code to perform the task. For example:
```
Given I am logged in as a user with “Content editor” role
```
This step is defined by a function within the Drupal extension; it takes “Content editor” as an argument, creates a basic user with that role assigned and logs that user in, so the scenarios can be performed from a perspective of Content editor, in this particular case.

Behat supports custom steps definitions via so called Contexts (read more here). The custom steps can be used to further expand on the existing contributed steps or add brand new definitions that can be tailored to specifically fit your system. A number of custom step definitions have been added to provide broader set of typically performed activities and cover some of the govCMS specifics. 

GovCMS already has a few custom step definitions that can be found in *build/tests/behat/bootstrap/FeatureContext.php* file. Some of those steps are slightly modified copies of the defaults from MinkContext or DrupalContext.

Due to a relatively big number of custom steps, it made a lot of sense to sort them out by some criteria. This was achieved with the sub-contexts approach available in Behat. The following sub-contexts and the steps that they supply (examples) were added to *build/tests/behat/bootstrap*:

1. **AccountContext.behat.inc**
```
Given I am logged in as a user named “John” with “Content editor” role
```
```
Given I am logged in as a user named “John” with the “administer site content,administer site configuration” permissions
```
```
Given I am logged in as a user with the password “ABC123” and the “administer site content” permission
```
```
Given I am logged in as a user named “John” with the following permissions: (list)
```
```
Given a user named “John” is deleted
```
```
Given a user named “John” has not logged in for “58” days
```
2. **ChosenContext.behat.inc**
```
When I set the chosen element “Tags” to “mytag”
```
3. **CkEditorContext.behat.inc**
```
Given CKEditor/WYSIWYG for the field “Body” exists
```
```
Then CKEditor/WYSIWYG for the field “Body” should exist
```
```
And I put “Hello” into CKEditor/WYSIWYG (of “Body” field)
```
```
Then CKEditor should contain “Hello”
```
```
Then CKeditor should match “/^def/” (regular expression)
```
```
When I execute the “bold” command in CKEditor
```
4. **MediaBrowserContext.behat.inc**
```
When I open the “Image” (field) media browser
```
```
When I submit the media browser
```
```
When I open the media browser for “Attach media” in “Documents” field set
```
```
When I select item “1” from the (id) media browser
```
5. **PermissionsCont [...]

2017-07-11 09:26 UTC, tobybellwood commented
Thanks @barbun - glad to see the tests passed their own tests :-)

2017-07-12 01:47 UTC, seanhamlin requested changes

2017-07-12 01:47 UTC, seanhamlin commented on CONTRIBUTING.md
> +*/build/tests/behat/bootstrap* to find the contexts that define some of the
I think you need to be careful about asterisks in markdown. Please either:

* use inline code blocks where appropriate
* escape the asterisk into HTML entity `&ast;`

I think for describing folders etc, you should use the first option `*/build/tests/behat/bootstrap*`

2017-07-12 01:47 UTC, seanhamlin commented on CONTRIBUTING.md
> +needed for Jenkins. The output will be placed in a */coverage* directory.
More asterisk fun.

2017-07-12 01:47 UTC, seanhamlin commented on build/composer.json
> +        "phpunit/phpunit": "^5.7"
this should be in require-dev.

2017-07-12 01:47 UTC, seanhamlin commented on build/tests/behat/bootstrap/ChosenContext.behat.inc
> +namespace Acquia\govCMSExtension\Context;
Unsure about this namespace, can we make this generic to govCMS?

2017-07-12 01:47 UTC, seanhamlin commented on build/tests/behat/bootstrap/MediaBrowserContext.behat.inc
> +    sleep(10);
Do we need this? Or how about waiting for the modal to be visible?

2017-07-12 01:47 UTC, seanhamlin commented on modules/custom/tdd7/LICENSE
> +                    GNU GENERAL PUBLIC LICENSE
No need for GPL license files inside modules in a GPL distribution.

2017-07-12 01:47 UTC, seanhamlin commented on modules/custom/tdd7/docs/README.md
> +	<?php
Using triple ```php is preferred as github adds syntax highlighting.

2017-07-12 01:47 UTC, seanhamlin commented on modules/custom/tdd7/docs/examples/tests/ExampleDrupalNodeMockTest.php
> + * @author Edward Murrell <edward@catalyst-au.net>
Should this module be brought in by composer? Rather than being inserted into the repo in it's entirety?

2017-07-12 01:48 UTC, seanhamlin commented on modules/custom/tdd7/docs/examples/tests/ExampleDrupalNodeMockTest.php
> + * @author Edward Murrell <edward@catalyst-au.net>
This review comment may supersede the above 2.

2017-07-12 02:17 UTC, barbun commented on modules/custom/tdd7/docs/examples/tests/ExampleDrupalNodeMockTest.php
> + * @author Edward Murrell <edward@catalyst-au.net>
We can, but I was a bit concerned that if repository goes away then the build process will be failing.

2017-11-28 04:06 UTC, pandaskii requested changes
Needs a clean PR only for automated testing

2018-02-28 20:21 UTC, tobybellwood commented
Closing - PR in #651

2018-02-28 20:21 UTC, closed without merging