[EXPERIMENTAL] add in TFA methods
govCMS/GovCMS7 pull request #695
Opened 2018-06-13 21:47 UTC by tobybellwood

This includes

- tfa module
- tfa_basic plugins
- Patch to tfa_basic (https://www.drupal.org/project/tfa_basic/issues/2090033) to provide email as a TFA option - needed for agencies without access to mobile phones.

2018-08-29 05:29 UTC, tobybellwood commented
Test this

2019-03-22 03:07 UTC, ruwanl commented on drupal-org.make
> +projects[tfa][version] = "2.0"
projects[tfa][patch][] = "https://www.drupal.org/files/issues/2019-02-07/tfa-2820710-42.patch"

2019-03-22 03:08 UTC, ruwanl commented on drupal-org.make
> +projects[tfa][version] = "2.0"
projects[tfa][patch][] = "https://www.drupal.org/files/issues/2019-02-07/tfa-2820710-42.patch"

2019-03-25 06:35 UTC, ruwanl requested changes
Can the patch be added to fix the issue at https://www.drupal.org/project/tfa/issues/2820710
projects[tfa][patch][] = "https://www.drupal.org/files/issues/2019-02-07/tfa-2820710-42.patch"

2019-03-25 23:45 UTC, ruwanl approved these changes

2019-03-27 02:12 UTC, tobybellwood commented
I've updated the email patch on this to the most recent available - this may provide a better outcome, it appears to be more PHP7.1 compatible.  If we can't get it to work, we will remove the email patch for now and proceed with TOTP-only auth whilst we work on other methods.

2019-03-28 00:25 UTC, pandaskii approved these changes
PR and two patches look good

Email patch - Drupal PHPUnit test failed for some reason but could be a false alarm.

We can cover the test case for email as available two-factor authentication method during the QA.

2019-05-31 01:03 UTC, merged