[GOVCMS-2012]: Support mobile phone numbers prefixed with 0499
govCMS/GovCMS7 pull request #762
Opened 2018-12-17 23:46 UTC by fubarhouse

2018-12-19 23:02 UTC, gargsuchi approved these changes

2018-12-19 23:13 UTC, gargsuchi requested changes
@fubarhouse 
why don't we upgrade workbench module to 7.x-3.0 instead of applying this patch? The project page also mentions this:

* The 7.x-3.x branch is the recommended version and the successor of the 7.x-1.x branch. If you're using a 7.x-1.x version you should consider updating to the 7.x-3.x as it fixes following security issue: SA-CONTRIB-2016-060

2018-12-20 01:58 UTC, fubarhouse commented
Previous discussions determined we will not be upgrading to the specified version, so the patch is the only path forward.

2018-12-21 06:33 UTC, gargsuchi approved these changes

2019-01-02 00:30 UTC, merged