[SA-Contrib-2018-077]: Apply recommended changes to password policy
govCMS/GovCMS7 pull request #768
Opened 2019-01-10 01:28 UTC by fubarhouse

This change is additional to #758 in that it introduces the recommended policy changes to the policies to prevent applicability to the vulnerability identified.

See #758 for a full breakdown and links to SA on drupal.org with this recommendation.

2019-01-18 04:35 UTC, pandaskii approved these changes
Happy to merge it after testing, thanks

2019-01-20 23:50 UTC, fubarhouse commented
As discussed I will also submit the changes to Behat tests to reflect the above change.
This will later translate to the `7.x.2.x` branch.

2019-01-21 01:33 UTC, pandaskii approved these changes
Thanks for the updated testing feature

2019-01-21 02:19 UTC, pandaskii requested changes

2019-01-21 02:19 UTC, pandaskii commented on tests/behat/features/configuration/password_policy.feature
> +    And the "constraint_digit" field should contain "1"
Is the field name "constraint_digit_placement" instead of "constraint_digit"?

2019-01-21 02:21 UTC, fubarhouse commented on tests/behat/features/configuration/password_policy.feature
> +    And the "constraint_digit" field should contain "1"
![image](https://user-images.githubusercontent.com/3070264/51449301-7d322080-1d7f-11e9-87d5-e1c95ce48ca6.png)

2019-01-21 02:26 UTC, pandaskii approved these changes

2019-01-21 03:29 UTC, fubarhouse commented on tests/behat/features/configuration/password_policy.feature
> +    And the "constraint_digit" field should contain "1"
My mistake - it's actually `constraint_digit_placement`.
I've just committed the changes.

2019-01-21 04:05 UTC, fubarhouse commented
Behat tests will cover this one off completely - tests look like they will pass now.

2019-01-21 04:13 UTC, merged

2019-01-21 04:13 UTC, pandaskii commented
Thanks, ready for release