Fixed undefined index notice.
govCMS/GovCMS7 pull request #886
Opened 2019-08-09 05:27 UTC by sonnykt

Fix the PHP notice
```
JIRA: https://jira.gold.gov.au/jira/browse/GOVCMSD7-208

2019-08-12 04:47 UTC, mingsong-hu approved these changes
Source code review passed. The error message should be gone with the new codes.

2019-08-12 05:29 UTC, pandaskii requested changes

2019-08-12 05:29 UTC, pandaskii commented on modules/custom/govcms_account_security/govcms_account_security.module
> +      if (empty($form['modules'])) {
Better to avoid a conditional break in a switch statement.

2019-08-12 05:29 UTC, pandaskii commented on modules/custom/govcms_account_security/govcms_account_security.module
>        foreach ($form['modules'] as $group => $value) {
Not sure foreach ((array)$form['modules'] as $group => $value) working or not

2019-08-12 05:30 UTC, pandaskii commented on modules/custom/govcms_account_security/govcms_account_security.module
>        // Disable the ability to change any configured modules.
Expecting to see "if statement" here, thanks

2019-08-12 05:55 UTC, AMDS commented on modules/custom/govcms_account_security/govcms_account_security.module
>        // Disable the ability to change any configured modules.
According to the official document, the PHP empty() function will check if a variable exists and if it is an empty array. Both cases, a TRUE value will be returned. Details see:
https://www.php.net/manual/en/function.empty.php

Therefore, I believe using the empty() function is good enough to avoid PHP warning message from generating.

2019-08-12 07:40 UTC, sonnykt commented on modules/custom/govcms_account_security/govcms_account_security.module
>        foreach ($form['modules'] as $group => $value) {
when `$form['modules']` does not exist, `(array) $form['modules']` still raises a notice.

2019-08-12 07:42 UTC, sonnykt commented on modules/custom/govcms_account_security/govcms_account_security.module
> +      if (empty($form['modules'])) {
`break` is completely fine in this `case`.

2019-08-12 23:14 UTC, simesy commented on modules/custom/govcms_account_security/govcms_account_security.module
>        // Disable the ability to change any configured modules.
Empty seems ok. I'd probably put it as the first thing inside the switch case as an "early return".

2019-08-13 03:33 UTC, pandaskii commented on modules/custom/govcms_account_security/govcms_account_security.module
>        foreach ($form['modules'] as $group => $value) {
Yes, you are correct

2019-08-13 03:40 UTC, pandaskii requested changes

2019-08-13 03:40 UTC, pandaskii commented on modules/custom/govcms_account_security/govcms_account_security.module
>        // Disable the ability to change any configured modules.
This is a good point. thanks @simesy

2019-10-31 23:53 UTC, pandaskii approved these changes

2019-10-31 23:54 UTC, pandaskii commented
Thanks @sonnykt

2020-04-05 23:57 UTC, merged